name: 'Deploy to App Engine'
author: 'Google LLC'
description: |-
  Deploy and promote a new service to Google App Engine.

inputs:
  project_id:
    description: |-
      The Google Cloud Project ID. If unspecified, it is inherited from the
      environment.
    required: true

  working_directory:
    description: |-
      The path to set the working directory. The deliverables will be referenced
      from this path.
    required: false

  deliverables:
    description: |-
      The yaml files for the services or configurations you want to deploy.
      If not given, defaults to app.yaml in the current directory. If that is
      not found, attempts to automatically generate necessary configuration
      files (such as app.yaml) in the current directory.
    required: false

  image_url:
    description: |-
      Deploy with a specific container image. The image URL must be from one of
      the valid GCR host names.
    required: false

  version:
    description: |-
      The version of the app that will be created or replaced by this
      deployment. If you do not specify a version, one will be generated for
      you.
    required: false

  promote:
    description: |-
      Promote the deployed version to receive all traffic.
    required: false
    default: "true"

  flags:
    description: |-
      Space separated list of other App Engine flags, examples can be found:
      https://cloud.google.com/sdk/gcloud/reference/app/deploy#FLAGS. Ex
      --service-account=my-account@project.iam.gserviceaccount.com --no-cache
    required: false

outputs:
  url:
    description: URL of your App Engine Application

branding:
  icon: 'code'
  color: 'blue'

runs:
  using: 'node16'
  main: 'dist/index.js'
