name: deploy-appengine Inputs Tests

on: [push, pull_request]

jobs:
  bad-input:
    if: ${{ github.event_name == 'push' || github.repository == github.event.pull_request.head.repo.full_name }}
    name: with bad inputs
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@master
      with:
        node-version: 12.x
    - name: Build dependency
      working-directory: setupGcloudSDK
      run: |-
        npm install
        npm run build
    - id: build
      name: Build dist
      run: |-
        npm install
        npm run build

    - name: Deploy fails with no credentials
      id: test2
      uses: ./
      continue-on-error: true
      with:
        project_id: ${{ secrets.APPENGINE_DEPLOY_PROJECT_ID }}
        working_directory: ${{ github.workspace }}/example-app/
    - name: Catch failure
      run: |-
        if [ ${{ steps.test2.outcome }} != 'failure' ]; then exit 1; fi
    
    - uses: google-github-actions/setup-gcloud@master
      with:
        service_account_key: ${{ secrets.APPENGINE_DEPLOY_SA_KEY_JSON }}

    - name: Deploy fails with no project Id
      id: test1
      uses: ./
      continue-on-error: true
      with:
        working_directory: ${{ github.workspace }}/example-app/
    - name: Catch failure
      run: |-
        if [ ${{ steps.test1.outcome }} != 'failure' ]; then exit 1; fi
        
